.TH DRIFTNET 1
.\"
.\" driftnet.1:
.\" Manual page for driftnet.
.\"
.\" Copyright (c) 2002 Chris Lightfoot. All rights reserved.
.\" Email: chris@ex-parrot.com; WWW: http://www.ex-parrot.com/~chris/
.\"
.\" $Id: driftnet.1,v 1.3 2002/05/26 23:45:03 chris Exp $
.\"

.SH NAME
driftnet - capture images from network traffic and display them in an X window.

.SH SYNOPSIS
.B driftnet
.B -h
| [
.B -i
.I interface
] [
.B -p
] [
.B -x
.I prefix
] [
.B -v
] [
.I filter code
]

.SH DESCRIPTION
\fBdriftnet\fP watches network traffic, and picks out and displays JPEG and GIF
images for display. It is an horrific invasion of privacy and shouldn't be
used by anyone anywhere. It has been described as `a graphical
.BR tcpdump(8)',
`\fIEtherPeg\fP for Unix', and called all sorts of nasty names by people on
.IR Freshmeat .

Images may be saved by clicking on them.

.SH OPTIONS

.TP
.B -h
Print a summary of usage.

.TP
\fB-i\fP \fIinterface\fP
Listen to packets on \fIinterface\fP. By default, \fBdriftnet\fP will try to
pick up traffic on all interfaces, but this does not work with all versions of
.BR pcap (3);
on such systems, an interface must be specified.

.TP
.B -p
Do not put the interface into promiscuous mode.

.TP
.B -v
Print additional details of packets captured to the terminal.

.TP
\fB-x\fP \fIprefix\fP
The filename prefix to use when saving images, by default `driftnet-'.

.TP
.I filter code
Additional filter code to restrict the packets captured, in the libpcap
syntax. User filter code is evaluated as `tcp and (\fIfilter code\fP)'.

.SH SEE ALSO
.BR tcpdump (8),
.BR pcap (3),
.br
.IR http://www.etherpeg.org/ ,
.br
.IR http://freshmeat.net/projects/driftnet/ ,
.br
.IR http://www.ex-parrot.com/~chris/driftnet/ .

.SH AUTHOR
Chris Lightfoot <chris@ex-parrot.com>

.SH VERSION
$Id: driftnet.1,v 1.3 2002/05/26 23:45:03 chris Exp $

.SH COPYING
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

